name: python-linter-and-formatter
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  pylint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: |
          shopt -s globstar && pylint --load-plugins pylint_django --django-settings-module=dutchmemocards.settings **/*.py
  black:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: |
          shopt -s globstar && black --check --verbose **/*.py
